### ISSUE TITLE
 Add publish interval ?

### ISSUE THREAD

**Issue by Thejul67** [schauveau/z2m_PJ-1203A#1]
Hello , 

Thanks for your awsome work about this power monitor device.

I have a request (maybe you cant do anything but i try ;) ):
This device send data every 10s , this is huge for my home assistant database.
More than 8000 values in 1 day :(

So my question is : Can we use this converter to publish only one value per minute (for exemple but if its customisable its better !) ? 

Thanks
Regards

**Comment by schauveau** [comment]
My 3 converters support a configurable  `update_frequency` attribute.  If I remember well, It also exists in the official converter but it is not declared as a setting so it is useless there. 

In  Home Assistant, it should appear as  `number.DEVICE_NAME_update_frequency` with a valid range between 3 and 60s.

I  am currently using a 3s delay but my install is pretty recent so I do not care yet about the size of the database. It is currently 167MB which is a lot but if I understand correctly, the values are discarded after 10 days so that should be manageable. 

I noticed that the device was sometime reverting to the 10s default. This is rare but that can happen. I am not sure why so you should probably install a system to reset it explicitly at regular interval.  

Also, the  value `update_frequency` displayed in HA and zigbee2mqtt is not always accurate. I think that the device is sending the datapoint but that seems to be very rare (every few hours?). Is there a way to query the actual value? More investigation are needed. 

Finally, make sure to disable the entities that you do not care about in either zigbee2mqtt or HA.

**Comment by schauveau** [comment]
I just had a quick look at the growing database problem. Here are my findings if that can help.

I wrote the following script to count the number of recorded events per entity:

```sh
#!/bin/sh
# Count the number of recordered entries per entity in the
# Home Assistant database (if using sqlite3)

DATABASE=/share/Docker/HomeAssistant/config/home-assistant_v2.db

sqlite3 "$DATABASE" 'SELECT COUNT(*), states_meta.entity_id  FROM states_meta, states where states_meta.metadata_id = states
.metadata_id GROUP BY states_meta.entity_id ORDER BY COUNT(*) ;'  ".exit ;"
``` 

As expected, the energy meter entities were the most common:
```
...

12803|sensor.plug_chauffe_eau_linkquality
14897|sensor.energy_meter_timestamp_b
14928|sensor.energy_meter_timestamp_a
20670|sensor.energy_meter_current_b
44934|sensor.energy_meter_current_a
50370|sensor.energy_meter_power_b
51237|sensor.0xa4c138078e510fdc_linkquality
92004|sensor.ssssss
106163|sensor.energy_meter_power_a
```

I was able to reduce its size using the `Recorder: Purge` service in HA but as mentioned previously that is done automatically every 10 days.  

Then I found this page https://www.home-assistant.io/integrations/recorder/

So I added the following lines to `configuration.yaml` to disable recording for some entities:

```yaml
recorder:
  exclude:
    entity_globs:
      - sensor.*_linkquality
    entities:
      - sensor.energy_meter_timestamp_a
      - sensor.energy_meter_timestamp_b
      - sensor.energy_meter_power_ab
      - sensor.energy_meter_current_a
      - sensor.energy_meter_current_b
      - sensor.energy_meter_power_factor_a
      - sensor.energy_meter_power_factor_b
``` 

I only keep `power_a` and `power_b` to be able to show them in graphs.   I also keep `energy_a`, `energy_b`,  `energy_produced_a` and  `energy_produced_b` since they are only updated every 5 minutes I believe.
